#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = '${BI_VIEWER_USER}'
    ) THEN
        EXECUTE format(
            'CREATE ROLE %I LOGIN PASSWORD %L',
            '${BI_VIEWER_USER}',
            '${BI_VIEWER_PASSWORD}'
        );
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${BI_VIEWER_USER};
GRANT USAGE ON SCHEMA public TO ${BI_VIEWER_USER};
GRANT USAGE ON SCHEMA mart TO ${BI_VIEWER_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${BI_VIEWER_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA mart TO ${BI_VIEWER_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${BI_VIEWER_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA mart GRANT SELECT ON TABLES TO ${BI_VIEWER_USER};
EOSQL
